### ISSUE TITLE
Results for Naturally pretrained models on downstream tasks? 

### ISSUE THREAD

**Issue by HashmatShadab** [dedeswim/vits-robustness-torch#1]
Thanks for this insightful work and for sharing the code.

May I ask if you have any results for natural pre-trained models when they are transferred to downstream tasks? Right now, the results are with adversarially pre-trained models. I'm curious to know if there have been any studies or experiments conducted on it, and what the findings might be.

 Thank you.

**Comment by dedeswim** [comment]
Hi,

Thanks for your interest in our work. We did not perform adversarial training on naturally pre-trained models, but, in case you are not familiar with it yet, you may find [this](https://arxiv.org/abs/1901.09960) work by Hendrycks et al. interesting.
