### ISSUE TITLE
Adversarial ImageNet pre-trained weights for DeiT and ConvNexT models.

### ISSUE THREAD

**Issue by HashmatShadab** [dedeswim/vits-robustness-torch#2]
Hi

Can you please provide weights for deit and convnext models? They are reported in Table IV of the paper.

**Comment by dedeswim** [comment]
Hi! You can already find the ConvNeXt-T weights [here](https://github.com/dedeswim/vits-robustness-torch/releases/download/v1.0/convnext_tiny-ImageNet-eps-4.pth.tar) and I have just uploaded the DeiT ones [here](https://github.com/dedeswim/vits-robustness-torch/releases/download/v1.0/deit-s-ImageNet-eps-4.pth.tar). More in general, the weights for most of the models reported in the paper are [here](https://github.com/dedeswim/vits-robustness-torch/releases/tag/v1.0).
Feel free to re-open the issue in case something is not clear.

**Comment by HashmatShadab** [comment]
Thanks !
